server:
  port: 80
spring:
  application:
    name: coin-gateway-serve
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        namespace: 4c55c5cb-068e-43f6-a8fa-fc86692b9509
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: coin-admin-service_router
          uri: lb://coin-admin-service
          predicates:
            - Path=/admin/**